version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-host
    network_mode: host
    command: redis-server --bind 0.0.0.0 --port 6379
    restart: unless-stopped
    ports:
      - "6379:6379"
